install.sh

Install script updated to support the matrix submodule.  
Matrix submodule updates are ignored via git config command.
Removed git reset/pull commands from install script.

Install script updates.

---

dimmer.py

Ensure that brightness from config file is within 0 to 100

Add check for brightness levels from config file 

---

boards/boards.py
boards/scoreticker.py
boards/standings.py
boards/team_summary.py
data/layout.py
main.py
renderer/logos.py
renderer/main.py
renderer/matrix.py
renderer/scoreboard.py

Used properly in scoreboard renderer, scoreticker & other boards work by passing an image.  Instead needs to use drawing functions on matrix class in the future.

Matrix class implemented.

---

src/boards/team_summary.py
src/data/layout.py
src/renderer/logos.py
src/renderer/main.py

No longer dependent on where script is run.

All files are loaded using get_file.

---

config/config.json
src/data/scoreboard_config.py
src/dimmer.py

Added frequency in minutes to sleep for dimmer to config file

fixed dimmer to be able to run on a pi zero.  

---

src/dimmer.py

Made tsl sensor an object usable throughout the class.  Light values are now properly calculated with sensor attached.

get tsl2591 working live

---

src/renderer/main.py

added ability to play two different animations,  one for preferred team and one for opposing team.

add dual goal animations

---

config/config.json.sample
src/nhl_setup/nhl_setup.py
src/sbio/pushbutton.py

Adds in covid_19 board.  Fixed nhl_setup creating dimmer and pushbutton config outside of sbio branch

Fixed pushbutton and nhl_setup for covid_19 board

---

src/nhl_setup/README.md
src/nhl_setup/nhl_setup.py

Better error messages and updated readme file to describe them.

Version 1.1 of nhl_setup app 

---

src/boards/covid_19.py
src/renderer/matrix.py

Added option to draw background when drawing text.

---

config/config.json.sample
src/nhl_setup/nhl_setup.py

Updated Canadian province nhl_setup error and fixed config,json.sample.

Updated Canadian province nhl_setup error and fixed config,json.sample.

---

src/nhl_setup/nhl_setup.py

to fix the spelling of the Leafs to Maple Leafs

Version 1.2.1 of nhl_setup app 

---

src/api/weather/ecAlerts.py
src/boards/clock.py
src/boards/wxAlert.py
src/boards/wxWeather.py

Fix for older code that existed that was causing ECX alerts to not trigger.  Also made the display drawing not use hard coded widths for the bars on the display so it will fill in full width on bigger displays (like 128x32 for example)

Fixes for EC alerts not firing 

---

src/api/weather/ecAlerts.py
src/api/weather/owmWeather.py
src/boards/wxAlert.py
src/boards/wxWeather.py
src/data/data.py
src/utils.py

This is a rewrite to allow the owmWeather.py to use the newest version of pyowm that was released at the end of May.  There were also a couple of tweaks on the weather alert board to pick how board looks based on alert feed and not the units.

owmWeather rewrite for compatibility with pyowm 3

---

src/renderer/main.py

On multi panel displays the end of period indicator and end of game indicator are not positioned correctly. This PR appropriately and dynamically positions the indicator.

Adds dynamic positioning for the end of pd/gm indicator

---

src/renderer/scoreboard.py

On multi-panel displays home PP indicator appears out of place. This PR will align it properly and dynamically.

Adds dynamic positioning for PP indicator

---

src/boards/seriesticker.py

On multi panel displays the size of the bars on the series board do not extend to the end of the display. This PR appropriately and dynamically sizes the bars.

Adds dynamic sizing to series board

---

README.md
src/data/data.py
src/nhl_setup/nhl_setup.py

The forecast board is called wxforecast

Added missing weather forecast board to be selectable in the setup app

---

src/boards/screensaver.py
src/sbio/screensaver.py

Fix for when the screensaver does have a previous board name set and also fixes for if the dimmer is not used and brightness not set on command line (this removes the fade in and fade out)

Screensaver fixes

---

.vscode/settings.json
src/config/file.py
src/config/files/fonts.py
src/config/files/layout.py
src/images/image_helper.py

Removed warnings from dynamic size files if they are not found.  Removed URL log.

Layout logo config now supports dynamic screen size

---

.gitignore
config/.default/config.json.sample
config/.default/config.schema.json

- Updated `.gitignore` with `config/*.config.json` line for possible backup files generated by GUI use.
- New schema and sample config copied to `config/.default/` folder.

Copied new schema and sample to .default and updated .gitignore

---

src/data/team.py

The __init__method for TeamScore contains some default values that are mutable.

Mutable values shouldn't be used as function argument defaults.

---

src/boards/team_summary.py
src/data/team.py

NHL's between season data updates left some team schedules in an inconsistent state. This traps the error that's tossed and displays '------' when the next or previous game can't be located in the team summary page.

Catch case where NHL's new calendar data isn't quite stable yet
